In [347]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
from graphviz import Source


In [348]:
FILENAME = f"data/{input('File Name (in data/)')}"
# FILENAME = f"data/processed_data.csv"
FILENAME

'data/1_3.csv'

In [349]:
rename_mark = { "220045" : "Heart Rate"                           , \
                "220210" : "Respiratory Rate"                     , \
                "220179" : "Non Invasive Blood Pressure systolic" , \
                "220180" : "Non Invasive Blood Pressure diastolic", \
                "220277" : "O2 saturation pulseoxymetry"          }

In [350]:
df = pd.read_csv(FILENAME, engine='python')
df.rename(columns=rename_mark, inplace=True)

In [351]:
# scale = StandardScaler()
df_spl, df_label_spl = df.drop(columns="label"), df["label"]
# df_spl = pd.DataFrame(scale.fit_transform(df_spl), columns=df_spl.keys())
X_train, X_test, y_train, y_test = train_test_split(df_spl, df_label_spl, test_size=0.2, stratify=df_label_spl)

In [352]:
from sklearn import tree
from sklearn.metrics import confusion_matrix

In [353]:
def test_mse(m):
    m.fit(X_train, y_train)
    a = m.predict(X_test)
    b = m.predict(X_train)
    A_score = mean_squared_error(a.astype('int'), y_test.astype('int'))
    B_score = mean_squared_error(b.astype('int'), y_train.astype('int'))
    return (round(A_score, 4), round(B_score, 4))
def test_model(m):
    A = m
    A.fit(X_train, y_train)
    y_pred = A.predict(X_test)
    cm=confusion_matrix(y_test,y_pred)
    print(cm)
    print(round(A.score(X_test, y_test), 2))
    print(test_mse(m))

In [354]:
len(X_train), len(X_test)

(1580, 396)

In [366]:
# 隨機森林
rfc = RandomForestClassifier(
    n_estimators=400, \
    max_depth=5, \
    max_leaf_nodes= 20
)
test_model(rfc)

[[158  40]
 [ 87 111]]
0.68
(0.3207, 0.2348)


In [358]:

# features = df.drop(columns="label").keys()
# dot_data = tree.export_graphviz(rfc[0], feature_names=features)
# graph = Source(dot_data)
# graph.render(view=True, format="pdf", filename=f"../Charts/forest{FILENAME}")

In [359]:
# 支持向量機
from sklearn.svm import SVC
clf = SVC(kernel='linear')
test_model(clf)

[[148  50]
 [ 87 111]]
0.65
(0.346, 0.3177)


In [364]:
from sklearn import linear_model
model=linear_model.LogisticRegression()
test_model(model)

[[145  53]
 [ 83 115]]
0.66
(0.3434, 0.3361)
